version: "3.8"
services:

  # Applications

  book-service:
    # Use ghcr.io/thomasvitale/gateway/book-service:routes on AMD64
    image: ghcr.io/thomasvitale/gateway/book-service:routes-arm64
    container_name: book-service
    labels:
      logging: "promtail"
    depends_on:
      - promtail
      - keycloak
    ports:
      - 9001:9001
    environment:
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411

  edge-service:
    # Use ghcr.io/thomasvitale/gateway/edge-service:routes on AMD64
    image: ghcr.io/thomasvitale/gateway/edge-service:routes-arm64
    container_name: edge-service
    labels:
      logging: "promtail"
    depends_on:
      - promtail
      - keycloak
    ports:
      - 9000:9000
    environment:
      - BOOK_SERVICE_URL=http://book-service:9001
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411

  # Backing Services

  redis:
    image: redis:7
    container_name: redis
    labels:
      logging: "promtail"
    ports:
      - 6379:6379
  
  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    container_name: "keycloak"
    labels:
      logging: "promtail"
    command: start-dev --import-realm
    volumes:
      - ./platform/keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080

  # Observability

  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    depends_on:
      - loki
      - prometheus
      - tempo
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./platform/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./platform/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./platform/grafana/grafana.ini:/etc/grafana/grafana.ini

  loki:
    image: grafana/loki:2.7.1
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.7.1
    container_name: promtail
    volumes:
      - ./platform/promtail/promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./platform/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo:1.5.0
    container_name: tempo
    command: -config.file /etc/tempo-config.yml
    ports:
      - "3110:3100"     # Tempo
      - "4317:4317"     # OTLP
      - "9411:9411"     # Zipkin
    volumes:
      - ./platform/tempo/tempo.yml:/etc/tempo-config.yml
